services:
  backend:
    build: .
    container_name: backend
    ports:
      - "80:80"
    volumes:
      - /src:/src/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: postgres_smit_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_DOCKER}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
